# Generated by Django 5.2.2 on 2025-06-08 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_student_created_at_student_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='user',
        ),
        migrations.AddField(
            model_name='student',
            name='clerk_user_id',
            field=models.CharField(default='default', max_length=255),
            preserve_default=False,
        ),
    ]
