# Generated by Django 5.2.2 on 2025-06-07 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0002_rename_title_assignment_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='date_completed',
            field=models.DateField(null=True),
        ),
    ]
