# Generated by Django 5.2.2 on 2025-06-07 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0003_alter_assignment_date_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='date_completed',
            field=models.DateField(blank=True, null=True),
        ),
    ]
